name: R2C-OpenWrt

on: workflow_dispatch
#  schedule:
#    - cron: 5 6 * * 0
#  watch:
#    types: started

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Download SDK
      run: |
        curl -LO ${{ secrets.sdks_url }}/openwrt-sdk-22.03.0-rockchip-armv8_gcc-11.2.0_musl.Linux-x86_64.tar.xz
    - name: show the file
      run: |
        ls ./ -la
