name: R2C-OpenWrt

on:
#  schedule:
#    - cron: 5 6 * * 0
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Download SDK
      run: |
        curl -LO ${{ secrets.sdks_url }}
    - name: show the file
      run: |
        ls ./ -la
